version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    networks:
      - aws-serverless-python-greetings_default
    ports:
      - "8000:8000"

networks:
  aws-serverless-python-greetings_default:
    external: true