version = 0.1
[default]
    [default.deploy]
        [default.deploy.parameters]
        stack_name = "vince-sam-app"
        s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w3zxm6r4xluu"
        s3_prefix = "vince-sam-app"
        region = "eu-west-1"
        confirm_changeset = false
        capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
